# Site settings
author: Cody Dupuis
title: The First Chapter Closes
header-img: img/home-bg.png
email: ctdupuis7@gmail.com
copyright_name: Cody Dupuis
description: > # this means to ignore newlines until "baseurl:"
  Learning Procedural and Object-Oriented Ruby
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ctdupuis

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
